export const posts = [
  {
    id: 0,
    slugID: 'Welcome-to-My-Blog:-An-Introduction-ldKJH98LKJdkfL',
    title: 'Welcome to My Blog: An Introduction.',
    bait: "Greetings and a warm welcome to my digital sanctuary, where the boundaries of technology, philosophy, and culture converge. I'm delighted that you've taken a moment to step into my world. Just as my portfolio website showcases my prowess as a Full-Stack Web Developer, this blog offers a broader canvas upon which I paint my passions, insights, and experiences for your enjoyment.",
    views: 23455,
    likes: 24343,
    dislikes: 3422,
    dateOfMaking: '20-09-2023',
  },
  {
    id: 1,
    slugID: 'Welcome-to-My-Blog:-An-Introduction-ldKJH98LKJdkfL',
    title: 'Welcome to My Blog: An Introduction 2.',
    bait: "Greetings and a warm welcome to my digital sanctuary, where the boundaries of technology, philosophy, and culture converge. I'm delighted that you've taken a moment to step into my world. Just as my portfolio website showcases my prowess as a Full-Stack Web Developer, this blog offers a broader canvas upon which I paint my passions, insights, and experiences for your enjoyment.",
    views: 23455,
    likes: 24343,
    dislikes: 3422,
    dateOfMaking: '20-09-2023',
  },
  {
    id: 2,
    slugID: 'Welcome-to-My-Blog:-An-Introduction-ldKJH98LKJdkfL',
    title: 'Welcome to My Blog: An Introduction 3.',
    bait: "Greetings and a warm welcome to my digital sanctuary, where the boundaries of technology, philosophy, and culture converge. I'm delighted that you've taken a moment to step into my world. Just as my portfolio website showcases my prowess as a Full-Stack Web Developer, this blog offers a broader canvas upon which I paint my passions, insights, and experiences for your enjoyment.",
    views: 23455,
    likes: 24343,
    dislikes: 3422,
    dateOfMaking: '20-09-2023',
  },
  {
    id: 3,
    slugID: 'Welcome-to-My-Blog:-An-Introduction-ldKJH98LKJdkfL',
    title: 'Welcome to My Blog: An Introduction 4.',
    bait: "Greetings and a warm welcome to my digital sanctuary, where the boundaries of technology, philosophy, and culture converge. I'm delighted that you've taken a moment to step into my world. Just as my portfolio website showcases my prowess as a Full-Stack Web Developer, this blog offers a broader canvas upon which I paint my passions, insights, and experiences for your enjoyment.",
    views: 23455,
    likes: 24343,
    dislikes: 3422,
    dateOfMaking: '20-09-2023',
  },
]