export const projects = [
  {
    id: 0,
    name: "Obsidian Git Sync",
    imgName: "obsidian-git-sync-cover-photo",
    imgUrl: "/obsidian-git-sync-cover-photo.png",
    imgAlt: "Obsidian Git Sync Full Cover Logo",
    imgWidth: 706,
    imgHeight: 240,
    imgBlurDataUrl: "obsidian-git-sync-cover-photo.png",
    status: "Live!",
    statusCode: "live",
    description: "ObsidianGitSync is an innovative synchronization tool specifically designed for users of the Obsidian note-taking application. This utility enables seamless syncing of your markdown notes to a remote Git repository, offering a free and secure alternative to the official Obsidian sync service. Optimized for Linux, it operates as a daemon, running quietly in the background, automatically detecting changes and committing them to your Git repository via SSH. With an easy-to-run bash script, installation and configuration are a breeze, allowing users to quickly set up their Obsidian workspace to sync with any Git remote. ObsidianGitSync provides a robust, privacy-focused solution for users to maintain their notes across devices while leveraging the powerful version control capabilities of Git.",
    liveUrl: "https://github.com/AbdifatahCodes/ObsidianGitSync",
    blogUrl: "/blog/posts/ObsidianGitSync-Crafting-a-Custom-Sync-Solution-for-Obsidian-Notes-GHFFfshf856fgh",
  },
  {
    id: 1,
    name: "Firepass",
    imgName: "firepass-cover-photo",
    imgUrl: "/firepass-cover-photo.png",
    imgAlt: "Firepass Full Cover Logo",
    imgWidth: 706,
    imgHeight: 240,
    imgBlurDataUrl: "firepass-cover-photo.png",
    status: "Coming Soon!",
    statusCode: "coming-soon",
    description: "Firepass redefines password security with its advanced, self-hostable manager built on Apollo-GraphQL and the Plasmo framework. Engineered for precision and ease, it offers a secure enclave to store and manage your passwords with the sophistication of enterprise-grade security measures. Streamline your digital life with Firepass, where powerful encryption meets the flexibility of Apollo-GraphQL, ensuring your credentials are always within reach yet safely under lock and key. Plasmo's dynamic frontend harmonizes with Firepass's robust backend, presenting a seamless user experience that's both intuitive and resilient. Embrace the future of password management with Firepass – your proactive step towards uncompromised digital security.",
    liveUrl: "https://github.com/AbdifatahCodes/firepass",
    blogUrl: "/blog",
  }
]