export const posts = [
  {
    id: 0,
    slugID: 'Welcome-to-My-Blog-An-Introduction-ldKJH98LKJdkfL',
    title: 'Welcome to My Blog: An Introduction.',
    bait: "Greetings and a warm welcome to my digital sanctuary, where the boundaries of technology, philosophy, and culture converge. I'm delighted that you've taken a moment to step into my world. Just as my portfolio website showcases my prowess as a Full-Stack Web Developer, this blog offers a broader canvas upon which I paint my passions, insights, and experiences for your enjoyment.",
    views: 0,
    likes: 0,
    dislikes: 0,
    dateOfMaking: '14-10-2023',
  },
  {
    id: 1,
    slugID: 'ObsidianGitSync-Crafting-a-Custom-Sync-Solution-for-Obsidian-Notes-GHFFfshf856fgh',
    title: 'ObsidianGitSync: Crafting a Custom Sync Solution for Obsidian Notes.',
    bait: "As a software developer and an advocate for cost-effective and efficient solutions, I embarked on an intriguing journey to create 'ObsidianGitSync,' a program designed to sync Obsidian notes to a Git repository. My motivation was simple: avoid the cost of Obsidian's official sync service and craft a tool tailored to my needs, with capabilities extending beyond available extensions.",
    views: 0,
    likes: 0,
    dislikes: 0,
    dateOfMaking: '17-11-2023',
  },
  {
    id: 2,
    slugID: 'Node.js-Security-Best-Practices-with-OAuth-&-JWT-Implementation-OHkkjajHIUhfjkdj',
    title: 'Node.js Security Best Practices with OAuth & JWT Implementation.',
    bait: "In the ever-evolving landscape of web development, Node.js has emerged as a beacon of efficiency and flexibility. This JavaScript runtime, built on Chrome's V8 engine, has revolutionized how developers conceive and implement server-side logic. Its non-blocking, event-driven architecture lends itself to the creation of scalable network applications, making it a preferred choice for many full-stack developers, especially those leveraging JavaScript's universality. However, with great power comes great responsibility, and this is particularly true when it comes to the realm of web application security.",
    views: 0,
    likes: 0,
    dislikes: 0,
    dateOfMaking: '20-12-2023',
  },
]